version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: yuktta-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yuktta
      POSTGRES_PASSWORD: yuktta123
      POSTGRES_DB: yuktta_bakes
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
